/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'iwata_katsuhiro' at '17/02/02 14:40' with Gradle 2.7
 *
 * @author iwata_katsuhiro, @date 17/02/02 14:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
